"""Single source of truth for the desktop UI's visual constants.

Every color, font size, spacing, gradient, theme palette, category color,
and trend palette consumed by the Qt frontend is declared here as an
immutable nested mapping. UI modules look up values via the ``TOKENS``
hierarchy instead of redeclaring hex codes or pixel sizes inline.

Pure-Python on purpose: this module lives under ``src/config/``, which
the project rule keeps free of ``PySide6`` imports. Pure data also makes
the same structure exportable to JSON for the upcoming web frontend, so
desktop and web cannot drift apart visually.
"""

from types import MappingProxyType

__all__ = ["TOKENS"]


def _freeze(value):
    """Recursively wrap dicts in ``MappingProxyType`` and lists in tuples."""
    if isinstance(value, dict):
        return MappingProxyType({key: _freeze(item) for key, item in value.items()})
    if isinstance(value, list):
        return tuple(_freeze(item) for item in value)
    return value


_THEME_DARK = {
    "bg_primary": "#1e1e1e",
    "bg_secondary": "#2b2b2b",
    "bg_card": "#23272f",
    "bg_card_alt": "#252526",
    "bg_input": "#252526",
    "bg_inset": "#20252c",
    "bg_hero": "#27303a",
    "bg_button": "#3f5261",
    "bg_button_hover": "#4b6478",
    "bg_button_pressed": "#32424f",
    "bg_disabled": "#2a2e33",
    "bg_search_card": "#27303a",
    "text_primary": "#f2f2f2",
    "text_secondary": "#c8c8c8",
    "text_muted": "#bdbdbd",
    "text_strong": "#dfe7ef",
    "text_disabled": "#8f969e",
    "text_on_accent": "#111111",
    "border": "#3c3c3c",
    "border_strong": "#404854",
    "border_subtle": "#44515b",
    "border_search": "#4d5d6b",
    "border_button": "#5f7384",
    "border_disabled": "#434952",
    "accent": "#FFD60A",
    "accent_hover": "#FFE27A",
    "accent_pressed": "#E0B800",
    "selection_bg": "#3f5261",
    "selection_text": "#ffffff",
    "painter_bg": "#20252c",
    "painter_text": "#eef3f8",
    "painter_subtext": "#bec7d2",
    "painter_label": "#d5dde8",
    "painter_box_border": "#516071",
    "painter_arrow_up": "#4fa3ff",
    "painter_arrow_down": "#ff5f5f",
    "painter_dot": "#4fa3ff",
    "solubility_soluble": "#2d8a4e",
    "solubility_insoluble": "#c0392b",
    "solubility_slightly": "#d4a017",
    "solubility_highlight": "#4fa3ff",
}

_THEME_LIGHT = {
    "bg_primary": "#fafafa",
    "bg_secondary": "#f0f2f5",
    "bg_card": "#ffffff",
    "bg_card_alt": "#f5f7fa",
    "bg_input": "#ffffff",
    "bg_inset": "#eef2f7",
    "bg_hero": "#e8eef6",
    "bg_button": "#d6dde6",
    "bg_button_hover": "#c5cdd9",
    "bg_button_pressed": "#b4bcc8",
    "bg_disabled": "#ececec",
    "bg_search_card": "#eef3fa",
    "text_primary": "#1a1d22",
    "text_secondary": "#3d4450",
    "text_muted": "#5a6270",
    "text_strong": "#1a1d22",
    "text_disabled": "#9aa1ad",
    "text_on_accent": "#1a1d22",
    "border": "#cfd4dc",
    "border_strong": "#b9c0c9",
    "border_subtle": "#cfd6e0",
    "border_search": "#a9b3c0",
    "border_button": "#9aa3b0",
    "border_disabled": "#d6d9de",
    "accent": "#1565c0",
    "accent_hover": "#1976d2",
    "accent_pressed": "#0d47a1",
    "selection_bg": "#bbdefb",
    "selection_text": "#0d47a1",
    "painter_bg": "#f5f7fa",
    "painter_text": "#1a1d22",
    "painter_subtext": "#3d4450",
    "painter_label": "#1a1d22",
    "painter_box_border": "#7d8794",
    "painter_arrow_up": "#1565c0",
    "painter_arrow_down": "#c62828",
    "painter_dot": "#1565c0",
    "solubility_soluble": "#1b5e20",
    "solubility_insoluble": "#b71c1c",
    "solubility_slightly": "#9a6b00",
    "solubility_highlight": "#1565c0",
}

_CATEGORY_DARK = {
    "alkali_metal": "#F28E2B",
    "alkaline_earth_metal": "#EDC948",
    "transition_metal": "#4E79A7",
    "post_transition_metal": "#2A9D8F",
    "metalloid": "#B07AA1",
    "nonmetal": "#E9D8A6",
    "halogen": "#FF66C4",
    "noble_gas": "#56CCF2",
    "lanthanide": "#CDB4DB",
    "actinide": "#9D4EDD",
}

_CATEGORY_LIGHT = {
    "alkali_metal": "#C46A12",
    "alkaline_earth_metal": "#9C8418",
    "transition_metal": "#2E5380",
    "post_transition_metal": "#1F7368",
    "metalloid": "#7F4F77",
    "nonmetal": "#A38B47",
    "halogen": "#C44099",
    "noble_gas": "#1F8AB3",
    "lanthanide": "#9077A4",
    "actinide": "#6E2DA0",
}

_RAW = {
    "color": {
        "theme": {
            "dark": _THEME_DARK,
            "light": _THEME_LIGHT,
        },
        "category": {
            "dark": _CATEGORY_DARK,
            "light": _CATEGORY_LIGHT,
        },
        "macro_class": {
            "metal": "#4E79A7",
            "metalloid": "#B07AA1",
            "nonmetal": "#EDC948",
        },
        "trend": {
            "numeric_gradient": {
                "start": "#2359A8",
                "end": "#FFD60A",
            },
            "directional": {
                "metallic": "#56CCF2",
                "nonmetallic": "#FFD60A",
            },
            "label_background_rgba": [20, 20, 20, 180],
        },
        "button_border": {
            "default": "#202020",
            "default_hover": "#FFFFFF",
            "focus": "#FFD60A",
            "search_match": "#FFD60A",
            "search_match_hover": "#FFF2A8",
            "pressed": "#000000",
            "selected": "#111111",
        },
        "fallback": {
            "ui": "#7A7A7A",
        },
        "text_on_color": {
            "dark": "#111111",
            "light": "#FFFFFF",
        },
        "info_panel": {
            "card_background": "#252526",
            "card_border_base": "#3C3C3C",
            "hero_border_base": "#44515B",
            "symbol_border_base": "#44515B",
            "meta_text_base": "#F2F2F2",
            "symbol_text_base": "#F2F2F2",
            "track_border_base": "#404854",
            "fill_color_base": "#7E8EA4",
            "category_border_target_white": "#FFFFFF",
            "subtle_border_base": "#55606D",
            "badge_secondary_text": "#F2F2F2",
            "empty_label_color": "#999999",
            "industrial_category_color": "#888888",
        },
        "metric_progress": {
            "track_rgba": [122, 122, 122, 24],
        },
    },
    "font": {
        "family": {
            "sans": "Segoe UI, Arial, sans-serif",
            "mono": "Consolas, Menlo, monospace",
        },
        "size": {
            "title": 24,
            "search_status": 12,
            "trend_status": 12,
            "builder_status": 11,
            "builder_scope": 11,
            "search_title": 16,
            "search_help": 11,
            "search_input": 14,
            "builder_value": 12,
            "builder_slot": 11,
            "builder_badge": 11,
            "builder_compact_button": 11,
            "info_label": 13,
            "compound_result": 13,
            "info_section_title": 11,
            "info_field_label": 11,
            "info_field_value": 14,
            "info_hero_atomic_number": 28,
            "info_hero_symbol": 44,
            "info_hero_name": 24,
            "info_hero_badge": 11,
            "diagram_title": 14,
            "header_label": 11,
            "transition_block": 14,
            "transition_block_min": 9,
            "element_symbol": 14,
            "element_symbol_min": 8,
            "element_number_min": 6,
            "side_label": 11,
            "series_label": 10,
            "input": 13,
            "button_default": 12,
            "panel_mini_button": 11,
            "selected_element_name": 20,
            "list_widget": 12,
            "info_industrial_category": 10,
        },
        "weight": {
            "regular": 400,
            "medium": 500,
            "bold": 700,
        },
        "letter_spacing": {
            "info_section_title": 0.4,
        },
    },
    "spacing": {
        "title_padding_bottom": 2,
        "info_card_padding": 12,
        "info_card_inner_gap": 12,
        "info_section_padding": 12,
        "info_section_gap": 10,
        "info_grid_h_gap": 12,
        "info_grid_v_gap": 8,
        "info_metric_gap": 4,
        "hero_inner_gap": 14,
        "hero_padding": 12,
        "hero_text_gap": 6,
        "hero_top_row_gap": 12,
        "hero_meta_h_gap": 12,
        "hero_meta_v_gap": 6,
        "hero_caption_gap": 2,
        "badge_gap": 6,
        "badge_padding_y": 4,
        "badge_padding_x": 10,
        "slot_badge_padding_y": 2,
        "slot_badge_padding_x": 8,
        "button_padding_y": 6,
        "button_padding_x": 10,
        "button_compact_padding_y": 5,
        "button_compact_padding_x": 9,
        "search_button_padding_x": 12,
        "input_padding": 6,
        "input_padding_focused": 5,
        "element_cell_padding_x": 6,
        "element_cell_padding_y": 4,
        "element_cell_padding_x_min": 2,
        "element_cell_padding_y_min": 2,
        "list_padding": 4,
        "list_item_padding": 6,
        "diagram_box_padding": 10,
        "compound_result_padding_y": 6,
        "compound_result_padding_x": 8,
        "info_label_padding": 12,
        "title_padding_top": 2,
        "isotopes_layout_gap": 8,
        "uses_layout_gap": 8,
    },
    "radius": {
        "info_card": 14,
        "search_card": 14,
        "info_section": 12,
        "info_hero": 12,
        "symbol_card": 12,
        "diagram_box": 12,
        "panel": 10,
        "compound_panel": 10,
        "badge": 11,
        "button": 8,
        "input": 8,
        "list": 8,
        "compound_result": 8,
        "selector_card": 8,
        "metric_progress": 4,
        "accent_bar": 3,
        "cell_min": 4,
        "cell_ratio": 0.16,
    },
    "border": {
        "default_width": 1,
        "input_focused_width": 2,
        "search_match_width": 3,
        "selected_width": 3,
        "focused_width": 3,
        "hover_width": 2,
        "pressed_width": 2,
        "hero_accent_bar_width": 6,
        "metric_progress_height": 8,
        "accent_bar_radius": 3,
    },
    "scale": {
        "metric_normalized": 1000,
        "info_hero_symbol_min_width": 72,
        "combo_box_min_width": 88,
        "search_input_min_height": 24,
        "combo_drop_down_width": 24,
        "element_cell_min_width": 40,
        "element_cell_min_width_floor": 18,
        "element_cell_min_height": 48,
        "element_cell_min_height_floor": 28,
    },
    "alpha": {
        "metric_track": 24,
        "hero_background": 34,
        "symbol_background": 22,
        "subtle_background": 34,
    },
    "interpolation": {
        "card_border_t": 0.24,
        "hero_border_t": 0.5,
        "symbol_border_t": 0.55,
        "meta_text_t": 0.26,
        "symbol_text_t": 0.35,
        "track_border_t": 0.38,
        "fill_color_t": 0.78,
        "category_border_t": 0.18,
        "subtle_border_t": 0.55,
    },
    "luminance": {
        "text_on_color_threshold": 160,
    },
}

TOKENS = _freeze(_RAW)
